# core/signal_post.py — gemeinsames Signal-Posting der Research-Bots 30–33.
#
# Bewusster Bruch der "send_signal inline pro Bot"-Konvention: die vier neuen
# Bots posten in DENSELBEN Channel (CH_NEW_IDEAS) mit identischer Semantik —
# eine Quelle verhindert die Doppel-Post-/Atomicity-Fehlerklasse (Fix vom
# 2026-07-06) statt sie vierfach zu kopieren.
#
# Vertrag (identisch 18_ai_abr1_bot.send_signal):
#   * Outbox-Zeilen (Cornix-Klartext + HTML-Info) und ai_signals-Insert laufen
#     in der OFFENEN Transaktion des Aufrufers — KEIN Commit hier. Der Aufrufer
#     schließt atomar ab (update_cooldown(commit=True) oder conn.commit()).
#   * Die HTML-Info-Nachricht wiederholt den Cornix-Block NICHT (Cornix parste
#     beide Nachrichten sonst als eigenständige Signale — Doppel-Position).

from __future__ import annotations

import datetime
import json
import logging

from core.charting import generate_minichart_image
from core.market_utils import get_max_leverage
from core.trade_utils import format_price

logger = logging.getLogger(__name__)


def has_open_ai_signal(conn, symbol: str, direction: str, model_tag: str) -> bool:
    """True, wenn für Modul/Coin/Richtung bereits ein offener Trade im
    AI-Monitor läuft (ai_signals-Zeile existiert bis zum Close)."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT 1 FROM ai_signals WHERE symbol = %s AND direction = %s AND model = %s",
            (symbol, direction, model_tag),
        )
        return cur.fetchone() is not None


def post_ai_signal(
    conn,
    channel_id: int,
    model_tag: str,
    symbol: str,
    direction: str,
    confidence: float,
    entry1: float,
    entry2: float,
    sl: float,
    targets: list[float],
    source_desc: str,
    n_show: int = 3,
    with_chart: bool = True,
    extra_info_lines: list[str] | None = None,
) -> None:
    """Signal in Outbox (Cornix + HTML) + ai_signals schreiben — ohne Commit."""
    lev = get_max_leverage(symbol, 20)

    lines = [
        f"📈 Signal for {symbol} 📈",
        f"🚨 Direction: {direction}",
        f"🚨 Leverage: {lev}",
        "🚨 Margin: Cross",
        f"🏦 CMP Entry: $ {format_price(entry1)}",
    ]
    # Einzel-Entry-Signale (FIF1: Original-FIFO-Geometrie) posten wie das
    # Quell-Format nur EINE Entry-Zeile — Cornix' Verhalten bei zwei
    # identischen Preis-Strings ist nicht verifiziert (vgl. format_price-Fix).
    if format_price(entry2) != format_price(entry1):
        lines.append(f"🏦 Entry 2: $ {format_price(entry2)}")
    for i, t in enumerate(targets[:n_show], 1):
        lines.append(f"💰 TP{i}: $ {format_price(t)}")
    lines += [
        f"💸 Stop Loss: $ {format_price(sl)}",
        f"🧠 Trade idea generated by AI module {model_tag}",
    ]
    cornix_msg = "\n".join(lines)

    emoji = f"🚀 AI {model_tag} LONG SIGNAL" if direction == "LONG" else f"💥 AI {model_tag} SHORT SIGNAL"
    info_lines = [
        f"<b>{emoji}</b>",
        f"<b>{symbol}</b>",
        f"<b>→ Direction: {direction}</b>",
        f"<b>→ ML Confidence: {confidence:.1%}</b>",
        f"<b>→ Time: {datetime.datetime.now(datetime.timezone.utc).strftime('%H:%M')} UTC | Modul: {model_tag}</b>",
        f"<b>→ Source: {source_desc}</b>",
    ]
    for extra in extra_info_lines or []:
        info_lines.append(f"<b>→ {extra}</b>")
    html = "<pre>" + "\n".join(info_lines) + "</pre>"

    chart_buf = generate_minichart_image(symbol, minutes=240) if with_chart else None

    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO telegram_outbox (channel_id, message) VALUES (%s, %s)",
            (channel_id, cornix_msg),
        )
        if chart_buf:
            cur.execute(
                "INSERT INTO telegram_outbox (channel_id, message, image_path) VALUES (%s, %s, %s)",
                (channel_id, html, chart_buf),
            )
        else:
            cur.execute(
                "INSERT INTO telegram_outbox (channel_id, message) VALUES (%s, %s)",
                (channel_id, html),
            )
        cur.execute(
            """INSERT INTO ai_signals (symbol, price, model, direction, confidence,
                                       entry1, entry2, sl, targets)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                symbol,
                float(entry1),
                model_tag,
                direction,
                float(confidence),
                float(entry1),
                float(entry2),
                float(sl),
                # P2.31: track exactly the published targets. The Cornix block above
                # shows targets[:n_show]; the AI monitor scores whatever is stored in
                # ai_signals.targets — storing the full list scored phantom TPs.
                json.dumps([float(t) for t in targets[:n_show]]),
            ),
        )
    logger.info(f"✅ {model_tag} Signal für {symbol} {direction} in Outbox gelegt.")


def log_prediction(
    conn,
    model_tag: str,
    symbol: str,
    direction: str,
    entry_price: float,
    confidence: float,
    posted: bool,
    dedup_hours: int = 4,
    legacy_tag: str | None = None,
) -> None:
    """ml_predictions_master-Eintrag (Shadow-Logging, Report 15 — Grundlage der
    4–8-Wochen-Shadow-Auswertung). Dedup wie 11_ai_mis_bot: dieselbe
    Modul/Coin/Richtung-Kombi höchstens einmal je ``dedup_hours``. Ohne Commit.

    ``legacy_tag`` (T-2026-CU-9050-042): der Dedup-Key IST der Modell-Tag, und der
    kippt beim Retrain-Rollout. Ohne den Alt-Tag im Fenster begänne die neue
    Generation ihre Dedup-Historie bei null und schriebe die Shadow-Zeilen
    desselben Coins doppelt. Gleicher oder fehlender Alt-Tag ⇒ No-op, der zweite
    Bind fällt weg. GESCHRIEBEN wird immer unter ``model_tag`` — die laufende
    Generation, nie der Alt-Tag.
    """
    now = datetime.datetime.now(datetime.timezone.utc)
    window = f"{int(dedup_hours)} hours"
    with conn.cursor() as cur:
        if legacy_tag and legacy_tag != model_tag:
            cur.execute(
                """SELECT 1 FROM ml_predictions_master
                   WHERE coin = %s AND direction = %s AND model_name IN (%s, %s)
                     AND time > NOW() - %s::interval""",
                (symbol, direction, model_tag, legacy_tag, window),
            )
        else:
            cur.execute(
                """SELECT 1 FROM ml_predictions_master
                   WHERE coin = %s AND direction = %s AND model_name = %s
                     AND time > NOW() - %s::interval""",
                (symbol, direction, model_tag, window),
            )
        if cur.fetchone():
            return
        # P3.10 (dead column, documented): trade_id is a hardcoded 0 here and in
        # every other ml_predictions_master writer (11/12/13/14/15/24/25 +
        # 10_pump_dump) — it is never back-filled by any UPDATE, so it carries no
        # information on this shared path. The ONE writer that stores a real
        # trade_id is 9_ai_sr_bot (binds the setup-trade id). Do not read this
        # column as a trade key for anything except 9_ai_sr rows.
        cur.execute(
            """INSERT INTO ml_predictions_master
               (trade_id, model_name, time, coin, direction, entry, confidence, posted)
               VALUES (0, %s, %s, %s, %s, %s, %s, %s)""",
            (model_tag, now, symbol, direction, float(entry_price), float(confidence), posted),
        )


def post_shadow_ai_signal(
    conn,
    model_tag: str,
    symbol: str,
    direction: str,
    confidence: float,
    entry1: float,
    entry2: float,
    sl: float,
    targets: list[float],
    n_show: int = 3,
    dedup_hours: int = 4,
    legacy_tag: str | None = None,
) -> bool:
    """Monitored-but-unposted Shadow-Trade (T-2026-CU-9050-125).

    Schreibt NUR die ``ai_signals``-Zeile — KEINE ``telegram_outbox``-Zeile.
    Damit greift der AI-Monitor (8_ai_trade_monitor, ungefilterter Read) das
    Bein auf, verfolgt Entry/TP/SL und schreibt beim Close eine
    ``closed_ai_signals``-Zeile unter ``model_tag`` — OHNE dass je eine Nachricht
    einen Kanal erreicht (ein Post braucht zwingend eine telegram_outbox-Zeile;
    der Monitor postet selbst nichts). So bekommt ein unterdrücktes/geshadowtes
    Bein eine realisierte Ergebnis-Historie für die spätere Auswertung.

    Zusätzlich wird die ``ml_predictions_master``-Shadow-Zeile (``posted=False``)
    via :func:`log_prediction` geschrieben — dieselbe Prediction-Historie wie
    heute, plus jetzt der überwachte Trade.

    Kein Commit (der Caller schließt die Transaktion). Rückgabe: True, wenn eine
    Shadow-Zeile geschrieben wurde; False, wenn bereits ein offener Shadow-Trade
    für (symbol, direction, model_tag) im Monitor läuft (Dedup gegen den
    Monitor-Arbeitssatz — spiegelt die Live-Dedup von :func:`has_open_ai_signal`).

    Der Aufrufer ruft das NUR am Nicht-Live-Zweig (leg ist SHADOW) — nie statt
    eines Live-Posts. targets[:n_show] werden getrackt (P2.31-Parität mit dem
    Live-Post: der Monitor scored genau die veröffentlichten TPs).
    """
    if has_open_ai_signal(conn, symbol, direction, model_tag):
        return False
    tps = [float(t) for t in targets[:n_show]]
    with conn.cursor() as cur:
        cur.execute(
            """INSERT INTO ai_signals (symbol, price, model, direction, confidence,
                                       entry1, entry2, sl, targets)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                symbol,
                float(entry1),
                model_tag,
                direction,
                float(confidence),
                float(entry1),
                float(entry2),
                float(sl),
                json.dumps(tps),
            ),
        )
    log_prediction(
        conn,
        model_tag,
        symbol,
        direction,
        entry1,
        confidence,
        posted=False,
        dedup_hours=dedup_hours,
        legacy_tag=legacy_tag,
    )
    logger.info("👻 %s SHADOW-Trade für %s %s in ai_signals (kein Cornix).", model_tag, symbol, direction)
    return True
