# core/signal_post.py — shared signal posting for research bots 30–33.
#
# Deliberate break from the "send_signal inline per bot" convention: the four new
# bots post to the SAME channel (CH_NEW_IDEAS) with identical semantics —
# one source prevents the double-post/atomicity error class (fixed on
# 2026-07-06) instead of copying it fourfold.
#
# Contract (identical to 18_ai_abr1_bot.send_signal):
#   * Outbox rows (Cornix plain text + HTML info) and the ai_signals insert run
#     in the caller's OPEN transaction — NO commit here. The caller
#     closes atomically (update_cooldown(commit=True) or conn.commit()).
#   * The HTML info message does NOT repeat the Cornix block (otherwise Cornix
#     would parse both messages as separate signals — double position).

from __future__ import annotations

import datetime
import json
import logging

from core import shadow_gate
from core.charting import generate_minichart_image
from core.market_utils import get_max_leverage
from core.trade_utils import format_price

logger = logging.getLogger(__name__)


def has_open_ai_signal(conn, symbol: str, direction: str, model_tag: str) -> bool:
    """True if a trade for module/coin/direction is already open in the
    AI monitor (ai_signals row exists until close)."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT 1 FROM ai_signals WHERE symbol = %s AND direction = %s AND model = %s",
            (symbol, direction, model_tag),
        )
        return cur.fetchone() is not None


def build_cornix_block(
    model_tag: str,
    symbol: str,
    direction: str,
    lev: str | int,
    entry1: float,
    sl: float,
    targets: list[float],
    n_show: int = 3,
) -> str:
    """The one Cornix-parsable message body, shared by every publisher.

    Extracted from ``post_ai_signal`` (T-2026-KYT-9050-042 Phase C) so the trailing
    bot mirrors signals into its own channel through the SAME builder. A second copy
    of this format is how a change like the entry2 removal below propagates to one
    publisher and not the other — the exact drift class hard rule 4 exists to prevent.
    Byte-identity with the pre-extraction output is pinned in
    ``backtest/test_trailing_post.py::test_cornix_block_is_shared``.

    Caller supplies ``lev`` because publishers differ on it: most take
    ``get_max_leverage(symbol, 20)``, UFI1 caps it against its SL (P0.6/R4), and a
    mirror has to reproduce whatever the source signal published.
    """
    lines = [
        f"📈 Signal for {symbol} 📈",
        f"🚨 Direction: {direction}",
        f"🚨 Leverage: {lev}",
        "🚨 Margin: Cross",
        f"🏦 CMP Entry: $ {format_price(entry1)}",
    ]
    # T-2026-KYT-9050-042 (operator decision, Michi): the entry2 DCA leg is no
    # longer PUBLISHED. The fleet trades single-entry — arm B of T-043/T-044/T-045,
    # where dropping the entry2 top-up lifted the Sharpe on 15/17 bots (median drag
    # +0.073) because the top-up averages into the losers. Nothing about the
    # GEOMETRY changes: entry2 is still computed, the SL still sits behind it, and
    # ai_signals.entry2 is still written — only the Cornix line is gone, so Cornix
    # fills the whole size at entry1. ROM1 (28_signal_orchestrator) deliberately
    # keeps publishing its own entry2 (its DCA was the one measured as neutral).
    for i, t in enumerate(targets[:n_show], 1):
        lines.append(f"💰 TP{i}: $ {format_price(t)}")
    lines += [
        f"💸 Stop Loss: $ {format_price(sl)}",
        f"🧠 Trade idea generated by AI module {model_tag}",
    ]
    return "\n".join(lines)


def post_ai_signal(
    conn,
    channel_id: int,
    model_tag: str,
    symbol: str,
    direction: str,
    confidence: float,
    entry1: float,
    entry2: float,
    sl: float,
    targets: list[float],
    source_desc: str,
    n_show: int = 3,
    with_chart: bool = True,
    extra_info_lines: list[str] | None = None,
) -> None:
    """Signal in Outbox (Cornix + HTML) + ai_signals schreiben — ohne Commit."""
    lev = get_max_leverage(symbol, 20)

    cornix_msg = build_cornix_block(model_tag, symbol, direction, lev, entry1, sl, targets, n_show)

    emoji = f"🚀 AI {model_tag} LONG SIGNAL" if direction == "LONG" else f"💥 AI {model_tag} SHORT SIGNAL"
    info_lines = [
        f"<b>{emoji}</b>",
        f"<b>{symbol}</b>",
        f"<b>→ Direction: {direction}</b>",
        f"<b>→ ML Confidence: {confidence:.1%}</b>",
        f"<b>→ Time: {datetime.datetime.now(datetime.timezone.utc).strftime('%H:%M')} UTC | Modul: {model_tag}</b>",
        f"<b>→ Source: {source_desc}</b>",
    ]
    for extra in extra_info_lines or []:
        info_lines.append(f"<b>→ {extra}</b>")
    html = "<pre>" + "\n".join(info_lines) + "</pre>"

    chart_buf = generate_minichart_image(symbol, minutes=240) if with_chart else None

    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO telegram_outbox (channel_id, message) VALUES (%s, %s)",
            (channel_id, cornix_msg),
        )
        if chart_buf:
            cur.execute(
                "INSERT INTO telegram_outbox (channel_id, message, image_path) VALUES (%s, %s, %s)",
                (channel_id, html, chart_buf),
            )
        else:
            cur.execute(
                "INSERT INTO telegram_outbox (channel_id, message) VALUES (%s, %s)",
                (channel_id, html),
            )
        cur.execute(
            """INSERT INTO ai_signals (symbol, price, model, direction, confidence,
                                       entry1, entry2, sl, targets)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                symbol,
                float(entry1),
                model_tag,
                direction,
                float(confidence),
                float(entry1),
                float(entry2),
                float(sl),
                # P2.31: track exactly the published targets. The Cornix block above
                # shows targets[:n_show]; the AI monitor scores whatever is stored in
                # ai_signals.targets — storing the full list scored phantom TPs.
                json.dumps([float(t) for t in targets[:n_show]]),
            ),
        )
    logger.info(f"✅ {model_tag} signal for {symbol} {direction} placed in outbox.")


def log_prediction(
    conn,
    model_tag: str,
    symbol: str,
    direction: str,
    entry_price: float,
    confidence: float,
    posted: bool,
    dedup_hours: int = 4,
    legacy_tag: str | None = None,
) -> None:
    """ml_predictions_master row (shadow logging, report 15 — basis for the
    4–8 week shadow evaluation). Dedup like 11_ai_mis_bot: the same
    module/coin/direction combo at most once per ``dedup_hours``. No commit.

    ``legacy_tag`` (T-2026-CU-9050-042): the dedup key IS the model tag, and it
    flips on a retrain rollout. Without the old tag in the window, the new
    generation would start its dedup history at zero and write the shadow rows
    for the same coin twice. Same or missing old tag ⇒ no-op, the second
    bind is dropped. It is always WRITTEN under ``model_tag`` — the current
    generation, never the old tag.
    """
    now = datetime.datetime.now(datetime.timezone.utc)
    window = f"{int(dedup_hours)} hours"
    with conn.cursor() as cur:
        if legacy_tag and legacy_tag != model_tag:
            cur.execute(
                """SELECT 1 FROM ml_predictions_master
                   WHERE coin = %s AND direction = %s AND model_name IN (%s, %s)
                     AND time > NOW() - %s::interval""",
                (symbol, direction, model_tag, legacy_tag, window),
            )
        else:
            cur.execute(
                """SELECT 1 FROM ml_predictions_master
                   WHERE coin = %s AND direction = %s AND model_name = %s
                     AND time > NOW() - %s::interval""",
                (symbol, direction, model_tag, window),
            )
        if cur.fetchone():
            return
        # P3.10 (dead column, documented): trade_id is a hardcoded 0 here and in
        # every other ml_predictions_master writer (11/12/13/14/15/24/25 +
        # 10_pump_dump) — it is never back-filled by any UPDATE, so it carries no
        # information on this shared path. The ONE writer that stores a real
        # trade_id is 9_ai_sr_bot (binds the setup-trade id). Do not read this
        # column as a trade key for anything except 9_ai_sr rows.
        cur.execute(
            """INSERT INTO ml_predictions_master
               (trade_id, model_name, time, coin, direction, entry, confidence, posted)
               VALUES (0, %s, %s, %s, %s, %s, %s, %s)""",
            (model_tag, now, symbol, direction, float(entry_price), float(confidence), posted),
        )


def _shadow_test_channel() -> int:
    """The optional shadow visibility channel (``config.CH_SHADOW_TEST``); 0 = off.

    Lazy import so signal_post stays decoupled/testable; DB-free tests
    monkeypatch this function instead of forcing config's import order.

    HARD guard (defense-in-depth, review fix): if CH_SHADOW_TEST is accidentally
    set to the TRADING channel (the only one Cornix reads), the echo is
    SUPPRESSED (return 0) — the "never the trading channel" invariant is thus
    enforced in code, not just operator discipline (rule 4).
    """
    from core import config

    ch = int(getattr(config, "CH_SHADOW_TEST", 0) or 0)
    trading = int(getattr(config, "REGIME_TRADING_CHANNEL_ID", 0) or 0)
    if ch and ch == trading:
        logger.warning("CH_SHADOW_TEST == trading channel — shadow echo suppressed (rule 4).")
        return 0
    return ch


def _shadow_preview_message(
    model_tag: str, symbol: str, direction: str, entry1: float, sl: float, tps: list[float]
) -> str:
    """Deliberately NOT Cornix-parsable shadow preview — pure visibility.

    Clearly marked as a non-trading signal; numbers as ``Ref-`` text WITHOUT the
    Cornix signal structure (no ``Entry:``/``Stop``/``Targets:`` triggers, no
    entry-zone/target-list layout), so that even a listening Cornix parser
    picks up NOTHING. Doubly safe: Cornix only listens to the trading
    channel anyway (REGIME_TRADING_CHANNEL_ID), this channel is a non-trading channel.
    """
    tp_txt = " / ".join(format_price(t) for t in tps) if tps else "—"
    # English, and deliberately NOT Cornix signal structure (no "Entry:"/"Targets:"/
    # "Stop Loss:" keywords, no entry-zone/target-list layout) — pure visibility.
    return (
        "👻 SHADOW PREVIEW — NOT a trade signal, no Cornix\n"
        f"Model {model_tag} · Coin {symbol} · Side {direction}\n"
        f"Ref-Entry {format_price(entry1)} · Ref-SL {format_price(sl)} · Ref-TPs {tp_txt}\n"
        "(monitored in ai_signals only — never reaches a trading channel)"
    )


def post_shadow_ai_signal(
    conn,
    model_tag: str,
    symbol: str,
    direction: str,
    confidence: float,
    entry1: float,
    entry2: float,
    sl: float,
    targets: list[float],
    n_show: int = 3,
    dedup_hours: int = 4,
    legacy_tag: str | None = None,
    expiry_hours: int | None = None,
    lev: str | None = None,
) -> bool:
    """Monitored-but-unposted shadow trade (T-2026-CU-9050-125).

    ``expiry_hours``/``lev`` (T-2026-KYT-9050-146, additive — default ``None``
    keeps every existing caller ROW-equivalent: both columns land NULL, exactly
    what the pre-extension INSERT produced via the column defaults; the
    statement itself now names both columns, which exist in docs/schema.sql and
    via the monitor's ADD COLUMN IF NOT EXISTS bootstrap): a shadow leg with a
    hard time-exit (the monitor closes it as ``HORIZON_TIMEOUT`` at the horizon
    end) can now carry that horizon on its own row, and ``lev`` records the
    operator's intended live leverage profile as metadata — the shadow trade
    itself is unlevered price tracking either way.

    Writes the ``ai_signals`` row and — if ``config.CH_SHADOW_TEST``
    is set (default 0 = off) — ONE deliberately non-Cornix-parsable preview
    to exactly this visibility channel. NEVER writes a Cornix-parsable
    telegram_outbox row and NEVER a row to the trading channel
    (T-2026-CU-9050-150). Without CH_SHADOW_TEST the behaviour stays
    exactly as before (only ai_signals, no channel).

    This lets the AI monitor (8_ai_trade_monitor, unfiltered read) pick up the
    leg, track entry/TP/SL and write a ``closed_ai_signals`` row under
    ``model_tag`` on close. A REAL (Cornix) post needs a Cornix-parsable row in
    the TRADING channel — that never happens here; the monitor posts nothing
    itself. This keeps the shadow trade risk-free and delivers a realized
    outcome history for later evaluation.

    Additionally the ``ml_predictions_master`` shadow row (``posted=False``)
    is written via :func:`log_prediction` — the same prediction history as
    today, plus now the monitored trade.

    No commit (the caller closes the transaction). Returns: True if a
    shadow row was written; False if an open shadow trade already exists
    for (symbol, direction, model_tag) in the monitor (dedup against the
    monitor working set — mirrors the live dedup of :func:`has_open_ai_signal`).

    The caller only calls this on the non-live branch (leg is SHADOW) — never
    instead of a live post. targets[:n_show] are tracked (P2.31 parity with the
    live post: the monitor scores exactly the published TPs).
    """
    if has_open_ai_signal(conn, symbol, direction, model_tag):
        return False
    tps = [float(t) for t in targets[:n_show]]
    with conn.cursor() as cur:
        cur.execute(
            """INSERT INTO ai_signals (symbol, price, model, direction, confidence,
                                       entry1, entry2, sl, targets, expiry_hours, lev)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                symbol,
                float(entry1),
                model_tag,
                direction,
                float(confidence),
                float(entry1),
                float(entry2),
                float(sl),
                json.dumps(tps),
                int(expiry_hours) if expiry_hours is not None else None,
                lev,
            ),
        )
    log_prediction(
        conn,
        model_tag,
        symbol,
        direction,
        entry1,
        confidence,
        posted=False,
        dedup_hours=dedup_hours,
        legacy_tag=legacy_tag,
    )
    # Optional visibility echo (T-2026-CU-9050-150): ONLY if CH_SHADOW_TEST
    # is set, and exclusively as a NON-Cornix preview to THIS channel —
    # never to the trading channel, never in Cornix format. In the same open
    # transaction (rule 8, the caller commits atomically with the ai_signals insert).
    test_ch = _shadow_test_channel()
    if test_ch:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO telegram_outbox (channel_id, message) VALUES (%s, %s)",
                (test_ch, _shadow_preview_message(model_tag, symbol, direction, entry1, sl, tps)),
            )
    logger.info("👻 %s SHADOW trade for %s %s in ai_signals (no Cornix).", model_tag, symbol, direction)
    return True


def post_ai_signal_gated(
    conn,
    tag: str,
    direction: str,
    channel_id: int,
    symbol: str,
    confidence: float,
    entry1: float,
    entry2: float,
    sl: float,
    targets: list[float],
    source_desc: str,
    n_show: int = 3,
    with_chart: bool = True,
    extra_info_lines: list[str] | None = None,
    dedup_hours: int = 4,
    legacy_tag: str | None = None,
) -> str | None:
    """Emits a (tag, direction) leg routed through the shadow_gate register
    (T-2026-CU-9050-183) — the central shadow→live promotion pattern:

      * ``LIVE``   → :func:`post_ai_signal` (Cornix + HTML + ``ai_signals`` to
        ``channel_id``, exactly ONE Cornix message, rule 4).
      * ``SHADOW`` → :func:`post_shadow_ai_signal` (monitored, no Cornix post).
      * else (``SILENT``/``RETIRED``) → no-op.

    This way a promotion flips purely via the ``_LIFECYCLE`` entry: SHADOW→LIVE
    switches the same bot from monitored to the real post, without duplicating
    the post branch. The caller has already checked cooldown/has_open
    and commits the transaction itself (rule 8). Returns: ``'live'`` |
    ``'shadow'`` | ``None`` (nothing emitted)."""
    st = shadow_gate.leg_status(tag, direction)
    if st == shadow_gate.LIVE and not channel_id:
        # Fail-safe (T-2026-CU-9050-183 review): a LIVE leg WITHOUT a configured
        # target channel (channel_id == 0, e.g. CH_ATS on an incorrectly set up
        # host) must NEVER write a Cornix row to channel 0 — it falls back to
        # the monitored shadow path (analogous to bot 33: CH_FIF1==0 ⇒ shadow-only).
        logger.warning("%s/%s is LIVE, but channel_id=0 — falling back to shadow post.", tag, direction)
        st = shadow_gate.SHADOW
    if st == shadow_gate.LIVE:
        post_ai_signal(
            conn,
            channel_id,
            tag,
            symbol,
            direction,
            confidence,
            entry1,
            entry2,
            sl,
            targets,
            source_desc,
            n_show=n_show,
            with_chart=with_chart,
            extra_info_lines=extra_info_lines,
        )
        return "live"
    if st == shadow_gate.SHADOW:
        wrote = post_shadow_ai_signal(
            conn,
            tag,
            symbol,
            direction,
            confidence,
            entry1,
            entry2,
            sl,
            targets,
            n_show=n_show,
            dedup_hours=dedup_hours,
            legacy_tag=legacy_tag,
        )
        return "shadow" if wrote else None
    return None


# ─────────────────────────────────────────────────────────────────────────────
# LEGACY DIRECT-POST ROUTER  —  fleet-lifecycle gate for bots that do NOT post
# via post_ai_signal_gated (T-2026-KYT-9050-033).
# ─────────────────────────────────────────────────────────────────────────────
# Return values (caller branches on this):
LEG_LIVE = "live"  # Default (unregistered leg): caller posts live as before.
LEG_SHADOW = "shadow"  # A monitored shadow trade was written HERE (no Cornix).
LEG_SKIP = "skip"  # SILENT/RETIRED, shadow globally off, or dedup block: write nothing.


def route_legacy_leg(
    conn,
    tag: str,
    direction: str,
    symbol: str,
    confidence: float,
    entry1: float,
    entry2: float,
    sl: float,
    targets: list[float],
    *,
    n_show: int = 3,
    dedup_hours: int = 4,
    legacy_tag: str | None = None,
) -> str:
    """Fleet-lifecycle routing at the emission point of a LEGACY direct-post bot
    (BR/BB/QM pattern, SRA1, RUB2, EPD2, ABR2, MIS2, … — bots 7/9/10/11/13/18/24/25),
    which build their Cornix message inline and do NOT run through
    :func:`post_ai_signal_gated` (T-2026-KYT-9050-033, audit T-032 reconfig).

    Unlike the gated router, this helper builds NO message — the bot keeps
    its own format/chart. It only decides WHETHER the bot may post live:

      * :data:`LEG_LIVE`   — leg is LIVE (default for ANY leg not listed in the
        shadow_gate register): the caller runs its existing
        Cornix + ``ai_signals`` write unchanged.
      * :data:`LEG_SHADOW` — leg is SHADOW: a monitored shadow trade
        (``ai_signals``, NO Cornix, rule 4) has already been written HERE; the
        caller skips its live write and commits the transaction
        (rule 8 — the helper does not commit itself).
      * :data:`LEG_SKIP`   — leg is SILENT/RETIRED, ``KYTHERA_SHADOW_POSTING=0``,
        OR an open shadow trade dedups the leg (has_open): write nothing.

    Safety contract (hard rules 1/2/4, identical to :mod:`core.shadow_gate`):
    default = LIVE ⇒ a bot whose (tag, direction) legs are NOT registered
    behaves BYTE-IDENTICALLY to before. The wiring is purely ADDITIVE at the
    post branch and can NEVER turn a live post into a shadow, unless the
    leg is explicitly entered as SHADOW. The caller has already checked
    cooldown/has_open of its live tag; the shadow branch additionally dedups via
    :func:`post_shadow_ai_signal`'s own has_open against the monitor working set.
    """
    st = shadow_gate.leg_status(tag, direction)
    if st == shadow_gate.LIVE:
        return LEG_LIVE
    if st == shadow_gate.SHADOW and shadow_gate.shadow_posting_enabled():
        wrote = post_shadow_ai_signal(
            conn,
            tag,
            symbol,
            direction,
            confidence,
            entry1,
            entry2,
            sl,
            targets,
            n_show=n_show,
            dedup_hours=dedup_hours,
            legacy_tag=legacy_tag,
        )
        return LEG_SHADOW if wrote else LEG_SKIP
    return LEG_SKIP
